name = "dne"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db45a08a4b8b73f372cb64ee4d925c8eb953e17359ea215b790ff01901bd126e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.117"
