name = "CmdgodPack"
author = "Cmdpro"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "05237bca4907a621b8a709321b192c2ff9d5ad0dab69433250c4e99e21d38fb2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.80"
