name = "CmdgodPack"
author = "Cmdpro"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e7ac7d60cb81257b76da5ec4573248a32ed23380e04b316bde83256b1c79d23"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.80"

[options]
acceptable-game-versions = ["1.21"]
