name = "CmdgodPack"
author = "Cmdpro"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d80e19f891802701e859ef97181c98ba8bd51a6d67dd333984f404fd7c737def"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.80"
